### ISSUE TITLE
Client options must not generate Getter style methods for retrievng members

### ISSUE THREAD

**Issue by skmcgrail** [awslabs/smithy-go#154]
This issue tracks the removal of the generated `GetXYZ() XYZ` methods from the client `Options` type. Getters are an anti-pattern that has quickly broken down when attempting to define "Getters" around members that are interface types. Specifically if a client attempts to decouple itself from an implementation by defining its own interface definition for an option member, the generated "Getter" would be unable to satisfy an interface that describes the same Getter but with an alternative (but matching) interface type.

As an example the following code would not allow the `client.Options{}` to be passed into `fooimpl.NewFooMiddleware`
```
package client

type FooInterface interface {
  DoThing() bool
}

type Options struct {
  Foo FooInterface
}

func (o *Options) GetFoo() FooInterface {
  return o.Foo
}
...
package fooimpl

type Foo interface {
  DoThing() bool
}

type FooImpl struct {}
func (f *FooImpl) DoThing() {
  return true
}

type FooMiddlewareOptions interface {
  GetFoo() Foo
}

func NewFooMiddleware(o Options) FooMiddleware {
  ...
}
```

**Comment by jasdel** [comment]
option getter removed
